### ISSUE TITLE
compile fails

### ISSUE THREAD

**Issue by icebluey** [kdave/btrfs-progs#336] opened 2021-01-29 16:40 UTC
btrfs-progs v5.10
rhel 7

build error:
    [LD]     btrfs
gcc -o btrfs btrfs.o kernel-shared/dir-item.o qgroup.o kernel-lib/list_sort.o props.o kernel-shared/ulist.o check/qgroup-verify.o kernel-shared/backref.o common/string-table.o common/task-utils.o kernel-shared/inode.o kernel-shared/file.o common/help.o cmds/receive-dump.o common/fsfeatures.o common/format-output.o common/device-utils.o cmds/subvolume.o cmds/filesystem.o cmds/device.o cmds/scrub.o cmds/inspect.o cmds/balance.o cmds/send.o cmds/receive.o cmds/quota.o cmds/qgroup.o cmds/replace.o check/main.o cmds/restore.o cmds/rescue.o cmds/rescue-chunk-recover.o cmds/rescue-super-recover.o cmds/property.o cmds/filesystem-usage.o cmds/inspect-dump-tree.o cmds/inspect-dump-super.o cmds/inspect-tree-stats.o cmds/filesystem-du.o mkfs/common.o check/mode-common.o check/mode-lowmem.o libbtrfs.a libbtrfsutil.a -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic -L.   -luuid   -lblkid   -lmount   -L. -pthread  -lz   -llzo2 -lzstd  

/bin/ld: libbtrfs.a(utils.o): in function `find_mount_fsroot':
/tmp/btrfs-progs-v5.10/common/utils.c:1331: undefined reference to `mnt_table_is_empty'
/bin/ld: /tmp/btrfs-progs-v5.10/common/utils.c:1339: undefined reference to `mnt_unref_cache'
/bin/ld: /tmp/btrfs-progs-v5.10/common/utils.c:1343: undefined reference to `mnt_unref_table'
collect2: error: ld returned 1 exit status
make: *** [Makefile:558: btrfs] Error 1
make: *** Waiting for unfinished jobs....

**Comment by kdave** [comment] 2021-01-29 19:57
Duplicate of #334, please continue there.

**Closed by kdave** 2021-01-29 19:57 UTC
