### ISSUE TITLE
mkswapfile short description is incorrect

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#558] opened 2022-12-20 20:16 UTC
When issuing an incomplete `btrfs fi` command to get a subcommand listing, the short summary for mkswapfile appears to be intended for `btrfs fi sync` rather than for `mkswapfile`.
```
$ sudo btrfs filesystem
usage: btrfs filesystem [<group>] <command> [<args>]
...
    btrfs filesystem mkswapfile <file>
        Force a sync on a filesystem
```

 btrfs --version
btrfs-progs v6.0.2
$ rpm -q btrfs-progs
btrfs-progs-6.0.2-1.fc37.x86_64

**Comment by kdave** [comment] 2022-12-20 20:47
This is a duplicate of #554, that's been fixed in devel. As it's a small problem I did not do a minor release so it'll be in 6.1.

**Closed by kdave** 2022-12-20 20:47 UTC
