### ISSUE TITLE
send: Send from snap on / fails

### ISSUE THREAD

**Issue by heftig** [kdave/btrfs-progs#162] opened 2019-01-19 23:40 UTC
Since 4.20, `btrfs send` fails for me:
```
~/vc/btrfs-progs> sudo btrfs send /mnt/snapshot-2019-01-19T23:25:29+00:00 >/dev/null 
ERROR: failed to determine mount point for /mnt/snapshot-2019-01-19T23:25:29+00:00: No such file or directory
```
The snapshot is part of the FS mounted at `/`.
4.19.1 works fine. Send from another FS not mounted at `/` works with 4.20, as well.

Bisected to commit cb8abddb20a0823c9dae5ab464a4f767d2268aca (Btrfs-progs: fix mount point detection due to partial prefix match).

Is this similar to #122?

**Comment by batGnat** [comment] 2019-01-24 12:54
Having same issue with 4.20, and btrfs-progs 4.20.1-1 
```
sudo btrfs subvolume snapshot -r /etc /etc/.snapshots/etc_backup
sudo btrfs send /etc/.snapshots/etc_backup | sudo btrfs receive -v /home/batgnat/.spinningDisk/backup
ERROR: failed to determine mount point for /etc/.snapshots/etc_backup: No such file or directory
```

**Comment by douzzer** [comment] 2019-01-28 22:05
Replicated here with btrfs-progs-4.20.1, and confirmed heftig's regression works.  At first glance, the right fix seems to be, at utils.c:2081 at commit dc1c561,

```
		if (strncmp(ent->mnt_dir, path, len) == 0 &&
		    (len == 1 || path[len] == '/' || path[len] == '\0')) {
```

This picks up the solitary-slash scenario.  For snapshots at / there aren't any possible longer matches, hence the bug.

**Comment by kdave** [comment] 2019-02-25 18:04
This is temporarily fixed in 4.20.2, reverting the patch that caused it.

**Comment by bmillwood** [comment] 2019-06-16 21:09
When I was affected by this issue, I worked around it by doing:

```
mkdir /mnt/workaround
mount --bind / /mnt/workaround
btrfs send /mnt/workaround/path/to/snapshot
```

**Comment by marcosps** [comment] 2020-03-25 04:17
@heftig @bmillwood can you reproduce using  recent version of btrfs-progs, since the patch was reverted?

**Comment by bmillwood** [comment] 2020-04-15 05:51
I'm on btrfs-progs v5.2.1 and no longer need the workaround.

**Comment by heftig** [comment] 2020-04-15 06:06
Seems to be fine.

**Comment by kdave** [comment] 2020-04-15 13:43
Thanks. I don't see which patch could have fixed that, we had a test (misc-tests/035-receive-common-mount-point-prefix) that reproduced the first problem but got disabled after the revert. The test still does not pass on 5.2.1 but at least your testing verifies the real usecase.

**Closed** 2020-04-15 13:43 UTC
Labels: bug
