### ISSUE TITLE
unexpected number of devices: 0 != 1

### ISSUE THREAD

**Issue by leszekdubiel** [kdave/btrfs-progs#630] opened 2023-05-21 20:02 UTC
Installed btrfs-progs from debian-backports and error occurs: 

```

# btrfs dev usa / 
ERROR: unexpected number of devices: 0 != 1


# btrfs --version 
btrfs-progs v6.2 

# btrfs fi show / 
Label: none  uuid: e5a0fde8-828d-4b8c-8792-9ffbee1ca90b
	Total devices 1 FS bytes used 54.54GiB
	devid    1 size 432.76GiB used 64.01GiB path /dev/sda3


# btrfs --version 
btrfs-progs v6.2 


# dpkg -l | grep btrfs-progs
ii  btrfs-progs                   6.2-1~bpo11+1                  amd64        Checksumming Copy on Write Filesystem utilities
```

**Comment by adam900710** [comment] 2023-05-22 02:10
Is the fs a seed device?

**Comment by leszekdubiel** [comment] 2023-06-11 12:19
No I have never used seeding concept. 

[https://btrfs.readthedocs.io/en/latest/Seeding-device.html](url)

**Comment by kdave** [comment] 2023-10-24 12:31
There was a recent bug and reported as https://github.com/kdave/btrfs-progs/issues/697 with the same problem but likely a different cause. I haven't seen the 0!=1 problem anywhere and the only known cause is the seeding device, which you don't use.

Possibly other causes could be related to device additions and deletions, or maybe ongoing deletion/replace, but for a single device that does not make sense. Is the problem still present or reproducible?

**Comment by Andy3153** [comment] 2023-10-25 00:46
Just got the same problem. Getting the message when asking to see filesystem usage. My setup is one LUKS container on one device formatted with Btrfs, no seeding devices. Using latest btrfs-progs 6.5.3 from Arch Linux repos.

**Comment by leszekdubiel** [comment] 2023-10-25 07:59
I cannot reproduce this bug. It doesn't appear any more.

**Comment by kdave** [comment] 2023-10-25 15:11
@Andy3153 If you have progs 6.5.3 then it's the known bug #697, I was asking if @leszekdubiel was observing the problem since 6.2 version. Appears not, so I can close this, thanks.

**Closed by kdave** 2023-10-25 15:11 UTC
Labels: bug
