### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by sbabic** [kdave/btrfs-progs#323] opened 2020-12-08 12:27 UTC
Sorry if I crosspost - I sent this before to linux-btrfs (it seems the wrong place).
I ask about license for btrfs-progs and related
libraries. I would like to use libbtrfsutils in a FOSS project, but this
is licensed under GPLv3 (even not LGPL) and it forbids to use it in
projects where secure boot is used.
Checking code in btrfs-progs, btrfs is licensed under GPv2 (fine !) and
also libbtrfs. But I read also that libbtrfs is thought to be dropped
from the project. And checking btrfs, this is linked against
libbtrfsutils, making the whole project GPLv3 (and again, not suitable
for many industrial applications in embedded systems).

**Comment by kdave** [comment] 2020-12-08 20:26
`libbtrfsutil` is supposed to be used a library, so it's LGPL 3, while the rest of the btrfs-progs is GPL 2.
`libbtrfs` was and ad-hoc export of some functionality and given that it's wrapped GPL 2 code, it can't be used as a library (headers + .so)

No code in btrfs-progs is GPL 3. There's the file libbtrfsutil/COPYIING (added in 502e2a3510c5db03) but in my understanding it's there to accompany libbtrfsutil/COPYING.LESSER, as it starts with

```
  This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.

  0. Additional Definitions.
[...]
```

**Comment by kdave** [comment] 2021-03-17 13:56
Related https://lore.kernel.org/linux-btrfs/YFHtnGvRH+QlwRN6@angband.pl/T/#u and https://bugs.debian.org/985400

The problem is that `btrfs` (GPL v2 only) statically links against libbtrfsutil (LGPL v3), which is not compatible: http://gplv3.fsf.org/dd3-faq#gpl-compat-matrix

That might might be convincing enough to relicence libbtrfsuiltil to LGPL v2.

**Comment by kdave** [comment] 2021-03-17 14:21
https://github.com/mpv-player/mpv/issues/2033 how a relicensing was done in another project.

**Comment by lorddoskias** [comment] 2021-04-06 14:00
Relicense request has been sent and by the looks of it it will be accepted. https://lore.kernel.org/linux-btrfs/20210317200144.1067314-1-ngompa@fedoraproject.org/T/

**Comment by kdave** [comment] 2021-04-19 13:22
Change to LGPL 2.1+ pushed to devel, closing.

**Closed by kdave** 2021-04-19 13:22 UTC
Labels: question
