### ISSUE TITLE
Scrub doesn't verify data checksum

### ISSUE THREAD

**Issue by wiesl** [kdave/btrfs-progs#103] opened 2018-03-04 16:39 UTC
```
btrfs-image -c 9 /dev/mapper/fedora-root /boot/btrfs.bim
# Restore, ATTENTION: mounted to / again ..., reboot necessary
btrfs-image -r /boot/btrfs.bim /dev/sdb

mkdir /new
mount /dev/sdb /new
# Scrub doesn't verify checksum, as btrfsck --check-data-csum has checksum errors and scrub hasn't ...
btrfs scrub start -B /new

man btrfs-scrub
btrfs scrub is used to scrub a btrfs filesystem, which will read all data and metadata blocks from all devices and verify checksums. Automatically repair corrupted blocks if there’s a correct copy available.

```
Fedora Kernel: 4.15.6-300.fc27.x86_64
btrfs-progs-4.11.1-3.fc27.x86_64

**Comment by wiesl** [comment] 2018-03-04 16:53
```
[root@fedoravm01 ~]# btrfsck --readonly /dev/sdb
Checking filesystem on /dev/sdb
UUID: 7bb1e7be-c83c-4cbb-a396-14c38393977c
checking extents
checking free space cache
cache and super generation don't match, space cache will be invalidated
checking fs roots
checking csums
checking root refs
found 1390985216 bytes used, no error found
total csum bytes: 1145744
total tree bytes: 63668224
total fs tree bytes: 56377344
total extent tree bytes: 4915200
btree space waste bytes: 11757730
file data blocks allocated: 2671611904
 referenced 1772920832

[root@fedoravm01 ~]# btrfsck --readonly --check-data-csum /dev/sdb 2>&1 | head -n 15
checking extents
checking free space cache
checking fs roots
checking csums
mirror 0 bytenr 12582912 csum 2566472073 expected csum 2879053995
mirror 0 bytenr 12587008 csum 2566472073 expected csum 2721784730
mirror 0 bytenr 12591104 csum 2566472073 expected csum 2909449019
mirror 0 bytenr 12595200 csum 2566472073 expected csum 2944693684
mirror 0 bytenr 12599296 csum 2566472073 expected csum 3070116340
mirror 0 bytenr 12603392 csum 2566472073 expected csum 543174804
mirror 0 bytenr 12607488 csum 2566472073 expected csum 67118815
mirror 0 bytenr 12611584 csum 2566472073 expected csum 2516577738
mirror 0 bytenr 12615680 csum 2566472073 expected csum 2547771727
mirror 0 bytenr 12619776 csum 2566472073 expected csum 2011923778
mirror 0 bytenr 12623872 csum 2566472073 expected csum 3637505257
```

Needs also clarification, I guess that in the first case only metadata csums are correct, but in the second case data checksum are due to the zeroed image not correct.

Missing real data checksum in scrub.

**Comment by adam900710** [comment] 2018-03-19 09:51
You're using btrfs-image, which won't restore data at all.
It should only be used for development usage, and kernel can refuse to do anything related to data for such restored image.

So it's not a bug.

**Comment by kdave** [comment] 2018-03-19 14:02
We could at least teach check and scrub about the metadump images so it does not falserly report the missing checksums.

**Comment by adam900710** [comment] 2018-03-19 14:20
Right, that should be fixed.

2018年3月19日 22:02，"kdave" <notifications@github.com>写道：

**Comment by kdave** [comment] 2018-03-19 16:21
Btw, @adam900710, quote only relevant part of the comment if you reply by mail. Github hides the trailing quoted text, but it's still visible in the mail.

**Comment by wiesl** [comment] 2018-03-19 19:15
> You're using btrfs-image, which won't restore data at all.

Yes, and that's exactly the reason it should detect the wrong/missing data (according to the docs filled with zeros). Therefore checksums can't be the same but they are not reported without the --check-data-csum switch.

**Comment by adam900710** [comment] 2018-04-03 05:31
> Therefore checksums can't be the same but they are not reported without the --check-data-csum switch.
Since kernel scrub knows this is just an image for debug purpose, it will just skip csum check.
Anyway, I'll make "btrfs check" to follow the same behavior.

Fix and test case under way.

**Comment by kdave** [comment] 2018-04-09 14:37
Fix added to devel, thanks.

**Closed by kdave** 2018-04-09 14:37 UTC
Labels: bug
