### ISSUE TITLE
Use space cache v2 by default

### ISSUE THREAD

**Issue by Conan-Kudo** [kdave/btrfs-progs#295] opened 2020-09-04 22:20 UTC
The v2 variant of the space cache stuff has been recommended for a _long_ time. Can we have this switched to the default now?

**Comment by Conan-Kudo** [comment] 2020-09-05 14:01
This Btrfs wiki states that "[t]he btrfs(8) command currently only has read-only support for v2. A read-write command may be run on a v2 filesystem by clearing the cache, running the command, and then remounting with space_cache=v2."

Is this still the case?

**Comment by Conan-Kudo** [comment] 2020-09-05 14:08
Fedora downstream discussion is happening here: https://pagure.io/fedora-btrfs/project/issue/24

**Comment by cmurf** [comment] 2020-09-05 17:38
It might be stale info, pretty sure user space tools can write v2 since commit 8c028efe4a31e15c0d106daf6218dedc373273c6 which is v4.19.

**Comment by cmurf** [comment] 2020-09-05 17:49
Also there's a few issues that need to be resolved:

- Mount sometimes claims it's using v2 but it actually isn't.
https://github.com/btrfs/btrfs-todo/issues/5
- Conversion is currently not ideal, by not completely clearing v1
https://lore.kernel.org/linux-btrfs/20200601175252.GC18421@twin.jikos.cz/
- Conversion of large file systems can delay the conversion mount for hours. @Zygo reports 11 hours for a 32T file system. Of course his use cases are atypical, hugely fragmented areas, an extent tree with thousands to tens of thousands of backrefs. But it might be better to only autoconvert e.g. < 2 TB file systems. Or perhaps some other metric to cheaply estimate how expensive the conversion will be.

**Comment by kdave** [comment] 2020-09-07 09:22
The is desired and will happen, once all the remaining things are done. You have mentioned some of them, my checklist is roughly this:

* [x] mkfs support (now in devel, option -R free-space-tree)
* [ ] switch from v1 to v2 leaves behind all v1 caches on disk, until the data get rewritten
* [ ] metadata consumption is larger as the space tracking is stored there, unlike v1 that has that in data chunks, the medatata chunk preallocation is not balanced and would require more aggressive allocation, otherwise more no-metadata enospc will happen v1 was better in that respect as there are typically more data chunks available, also storing metadata in data is sort of cheating that let us get by
* [ ] there's one unfixed warning, fs/btrfs/block-group.c:125 btrfs_put_block_group+0x63 when cleaning up transaction after EIO (reported elsewhere)

Besides that, the documentation needs some updates, eg. how to migrate from v1 to v2, possibly avoiding the long delays like you mention.

**Comment by boryas** [comment] 2020-09-17 23:28
> there's one unfixed warning, fs/btrfs/block-group.c:125 btrfs_put_block_group+0x63 when cleaning up transaction after EIO (reported elsewhere)

Any idea on how to reproduce this? Or a reference to that report?

**Comment by kdave** [comment] 2020-09-18 14:02
https://github.com/btrfs/fstests/issues/17
https://github.com/btrfs/fstests/issues/9
https://github.com/btrfs/fstests/issues/11

**Comment by foundObjects** [comment] 2020-11-28 21:31
> Besides that, the documentation needs some updates, eg. how to migrate from v1 to v2, possibly avoiding the long delays like you mention.

What is the recommended process for moving from v1 to v2 at the moment? I've looked but it's not clearly spelled out anywhere that's easy to find (or if it is I've managed to totally miss it.)

**Comment by boryas** [comment] 2020-11-29 08:50
I believe that on most systems, it isn't really possible to upgrade the root filesystem to space_cache=v2 on reboot because most boot procedures first mount the root fs read-only, then remount it read-write, which doesn't currently support enabling the free space tree. It's also impossible to create the tree while mounting a read only filesystem, even for the first time. So your system would have to boot up and mount the root filesystem read-write directly with the new space_cache=v2 option, which is verging into the "boot from live media" domain, at least in my experience.

I am currently working on supporting read-only->read-write remounts enabling space_cache=v2 for exactly this case, though that is probably of little immediate help to you, unfortunately.

**Comment by kdave** [comment] 2020-12-01 16:04
> What is the recommended process for moving from v1 to v2 at the moment? I've looked but it's not clearly spelled out anywhere that's easy to find (or if it is I've managed to totally miss it.)

> spinics.net/lists/linux-btrfs/msg106846.html

It will be properly documented in manual pages and on the wiki, so far this was missing some fixes (queued for 5.11), the how-to was help from community, which is fine but we need to put that to the docs.

**Comment by kdave** [comment] 2020-12-01 16:07
I've updated the comment above tracking the remaining things to fix, the last one is higher demand for metadata and allocator update.

**Comment by Forza-tng** [comment] 2021-09-18 19:59
Perhaps the simplest upgrade path is to make `mkfs.btrfs -R free-space-tree` default?

This will lead to a gradual move to v2 which is easier for the community to support.

**Comment by foundObjects** [comment] 2021-09-19 08:15
As an end user I really like this approach, I think it's worth serious
consideration.

**Comment by kdave** [comment] 2021-09-27 22:20
Convert cannot do space_cache=v2 yet, related issue #408.

**Comment by kdave** [comment] 2021-09-30 14:54
Free space tree scheduled for default in 5.15.

**Comment by kdave** [comment] 2021-11-04 17:52
>     * [ ]  metadata consumption is larger as the space tracking is stored there, unlike v1 that has that in data chunks, the medatata chunk preallocation is not balanced and would require more aggressive allocation, otherwise more no-metadata enospc will happen v1 was better in that respect as there are typically more data chunks available, also storing metadata in data is sort of cheating that let us get by

The metadata allocation stands but needs to be fixed in kernel.

**Comment by kdave** [comment] 2021-11-04 17:52
All set for v2 by default, closing.

**Closed by kdave** 2021-11-04 17:52 UTC
Labels: enhancement, kernel, mkfs, convert, defaults

**Comment by MartinX3** [comment] 2021-12-15 19:29
@kdave I don't see this change in the CHANGELOG or in the btrfs kernel wiki.
I just stumpled over this change after creating a new btrfs partition and wondering why space cache is now default.
