### ISSUE TITLE
btrfs prop set causing system to reboot

### ISSUE THREAD

**Issue by axet** [kdave/btrfs-progs#699] opened 2023-10-26 17:16 UTC
Hello!

sudo find "/dev/snd" -exec btrfs prop set {} compression zstd \;

causing system to stuck with /dev/snd/pcmC1D0p file and then insta reboot after 5 minutes.

Also prop set stuck with following (~/.local/share/parcellite/fifo_c):

```
prw-r----- 1 axet axet   0 окт  7 13:42 fifo_c
```

6.1.0-13-amd64
btrfs-progs                                   6.2-1
debian 12

**Comment by kdave** [comment] 2023-10-31 00:25
So this is trying to set compression on a device node. I haven't looked but yeah this could cause problems.

Do you have any stack traces or last messages before reboot? Do you have enabled options like panic_on_warn, it could be something (relatively) harmless but when the system is configured to reboot on such problems it's going to make it worse.

**Comment by axet** [comment] 2023-10-31 15:36
How could be here a stack trace? I guess this call causing memory leaks or watchdog rebooting the kernel.

```
ls -al /dev/snd/pcmC1D0p
crw-rw----+ 1 root audio 116, 5 окт 31 17:50 /dev/snd/pcmC1D0p
```

**Comment by kdave** [comment] 2023-10-31 15:58
Ok, so it's watchdog, the process is stuck trying to read from snd device. For the fifo file the open() is blocked until the other end is opened (per manual page), this can be fixed by O_NONBLOCK. The same applies for the sound device, it fails right away with `ERROR: failed to open pcmC0D0p: Device or resource busy`.

**Comment by kdave** [comment] 2023-10-31 23:08
The CI fails for weird reasons with the fix, loop devices seem to be half initialized and mount fails saying multi-device filesystem devices cannot be found. https://github.com/kdave/btrfs-progs/actions/runs/6712572409 and other failed build tests with fix attempts (sleep, sync, udevadm settle). Reverting the commit fixes the problem. I'll need to find alternate solution, so this fix won't make it to 6.6.

**Comment by axet** [comment] 2023-11-01 06:29
Alternative? Let me guess:

```
btrfs prop set -r / compress=lzo
````

**Comment by kdave** [comment] 2023-11-01 21:32
I mean a different way to fix it but it seems that the CI failures were not related to this patch so I'll add it back to 6.6 queue.

**Comment by kdave** [comment] 2023-11-03 17:27
Fix in devel.

**Comment by axet** [comment] 2023-11-03 17:53
With patch:

```
 find /dev/snd/ -exec btrfs prop set {} compress zstd \;
ERROR: object is not a btrfs object: /dev/snd/
ERROR: object is not a btrfs object: /dev/snd/controlC1
ERROR: object is not a btrfs object: /dev/snd/hwC1D0
ERROR: object is not a btrfs object: /dev/snd/pcmC1D0c
ERROR: failed to open /dev/snd/pcmC1D0p: Device or resource busy
ERROR: object is not a btrfs object: /dev/snd/pcmC1D0p
ERROR: object is not a btrfs object: /dev/snd/by-path
ERROR: object is not a btrfs object: /dev/snd/by-path/pci-0000:03:00.6
ERROR: object is not a btrfs object: /dev/snd/by-path/pci-0000:03:00.1
ERROR: object is not a btrfs object: /dev/snd/controlC0
ERROR: object is not a btrfs object: /dev/snd/hwC0D0
ERROR: object is not a btrfs object: /dev/snd/pcmC0D3p
ERROR: object is not a btrfs object: /dev/snd/seq
ERROR: object is not a btrfs object: /dev/snd/timer
root@axet-laptop:/home/axet# 
```

machine still got rebooted after ~ 5 mins

**Comment by kdave** [comment] 2023-11-03 20:51
Ok, so that was only a partial fix for the hang on file open. The properties only set extended attributes, it is possible that this is interpreted by watchdog as reboot trigger or blocks the keep-alive pings, I don't know and more investigation is needed.

As a workaround I'll add exception for character files for properties.

**Comment by kdave** [comment] 2023-11-14 14:57
The workaround is now in devel. I can't reproduce the watchdog so I'd appreciate if you could test it, thanks.

**Comment by axet** [comment] 2023-11-14 15:32
Working fine! Thanks!

**Comment by kdave** [comment] 2023-11-15 14:42
Thank you, 6.6.2 on the way.

**Closed by kdave** 2023-11-15 14:42 UTC
Labels: bug
